### ISSUE TITLE
[Discussion] SCI aggregation views and intentions

### ISSUE THREAD

**Issue by perkss** [Green-Software-Foundation/standards-wg#111]
Now that the SCI has been calculated for software what are the next steps other than reduce. Would be great to hear peoples answers to these questions.

* Is the intention to aggregate the SCI to include multiple parts of software, take it to a department level/company level? IF Framework has built in aggregation of the metrics but is SCI meant to be used like this? In this case don't divide it by R but use the totals. 

* How can software engineers applying the SCI to individual software/process ensure  overall organisation emissions are being reduced as consequence?

* Are companies planning to (or GSF would like to have) report on SCI publicly? If so at what granularity? Or is the intention for other metrics to be used? Are there recommendations for this? 

* What are the recommendations on scaling the SCI calculations to company scale?

**Comment by Henry-WattTime** [comment]
WG Discussion:
- It's hard to apply at the organizational level because of the lack of functional unit
- It's specific functional unit
- Danger if it gets confused with corporate reporting
- At base, it's a KPI that can be improved 

Corporate reporting:
- Software is usually a small slice of an organization's software
- ex: Netflix emissions are actually in film/show production

SCER is interesting because it allows comparability and software selection.

SCI should be a system view, and not have an adverse effect on other parts of the organization by pushing emissions to other parts of the tech stack
ex. carbon per user journey, encapsulates whole emissions impact of interaction

**Comment by perkss** [comment]
Thanks @Henry-WattTime
