### ISSUE TITLE
[Case Study] MSFT/DOW Data updates

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#22]

**Comment by Henry-WattTime** [comment]
Just submitted case study just submitted, in Github. Review/formatting issues. Dow folks to present as well next week.

**Comment by tmcclell** [comment]
By moving the workload to West US region instead of North Central, we were able to reduce the carbon overall by 44%. <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Total SCI | Tiger   Graph DB + API, Neo4J DB + API
-- | --
321.35 gCO2e | 41.08 + 34.3 + 41.18 + 63
44% Reduction | 179.48 - Total   Difference (-141.95 gCO2e)



</div>


</body>

</html>
